In [1]:
import numpy as np

## Datatypes and attributes

In [15]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [16]:
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[1,2,3.0],
               [4,5.6,6],
               [7,8.8,9]])
a3 = np.array([[[1,2,3],[4,5,6]],[[5,5,5],[6,6,6]]])

In [8]:
a2

array([[1. , 2. , 3. ],
       [4. , 5.6, 6. ],
       [7. , 8.8, 9. ]])

In [12]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 5, 5],
        [6, 6, 6]]])

In [18]:
a1.shape

(5,)

In [19]:
a2.shape

(3, 3)

In [20]:
a3.shape

(2, 2, 3)

In [21]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [22]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [23]:
a1.size, a2.size, a3.size

(5, 9, 12)

In [24]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [25]:
# Create A DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.6  6.0
2  7.0  8.8  9.0

## 2. Create NumPy Arrays

In [27]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [28]:
sample_array.dtype

dtype('int64')

In [29]:
ones = np.ones((2,3))

In [30]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [34]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[4, 3, 7, 7, 1],
       [7, 3, 7, 8, 5],
       [6, 5, 2, 1, 8]])

## Viewing array and matrices

In [35]:
np.unique(random_array)

array([1, 2, 3, 4, 5, 6, 7, 8])